<a href="https://colab.research.google.com/github/jjzsilva9/imlo/blob/main/practical2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# IMLO Practical #2

In [2]:
import numpy as np

**Question 1:**

In [4]:
x = np.array([2, 3, 5])
v = np.array([3, 0, 4])

np.transpose(x) @ v

26

In [5]:
x @ np.transpose(v)

26

In [6]:
A = np.array([[4, 1, 0, 2], [2, 0, 1, 3]])
b = np.array([3, 0, 5, 1])

A @ b

array([14, 14])

In [7]:
B = np.array([[3, 2, 0], [0, 4, 2], [5, 0, 1], [1, 3, 4]])

A @ B

array([[14, 18, 10],
       [14, 13, 13]])

In [8]:
w = np.array([2, 4, 3, 1])
np.linalg.norm(w)

5.477225575051661

In [9]:
e = np.array([5, 0, 0])
e / np.linalg.norm(e)

array([1., 0., 0.])

**Question 2**

In [15]:
B[1:3, 1]

array([4, 0])

In [ ]:
def dot(v1, v2):
