<a href="https://colab.research.google.com/github/jjzsilva9/imlo/blob/main/practical2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# IMLO Practical #2

In [1]:
import numpy as np

**Question 1:**

In [2]:
x = np.array([2, 3, 5])
v = np.array([3, 0, 4])

np.transpose(x) @ v

26

In [3]:
x @ np.transpose(v)

26

In [4]:
A = np.array([[4, 1, 0, 2], [2, 0, 1, 3]])
b = np.array([3, 0, 5, 1])

A @ b

array([14, 14])

In [5]:
B = np.array([[3, 2, 0], [0, 4, 2], [5, 0, 1], [1, 3, 4]])

A @ B

array([[14, 18, 10],
       [14, 13, 13]])

In [6]:
w = np.array([2, 4, 3, 1])
np.linalg.norm(w)

5.477225575051661

In [7]:
e = np.array([5, 0, 0])
e / np.linalg.norm(e)

array([1., 0., 0.])

**Question 2**

In [10]:
B[1:3, 1]
np.dot(A, B)

array([[14, 18, 10],
       [14, 13, 13]])

In [14]:
def dot(v1, v2):
  if len(v1) != len(v2):
    return None
  ans = 0
  for k in range(len(v1)):
    ans += v1[k] * v2[k][0]
  return ans

dot([1, 3, 2], [[2], [4], [1]])

16

In [22]:
data = np.array([[1, 17, 9],
                [2, 21, 10],
                [3, 12, 17]])

np.dot(data, [0, 1, 1])

array([26, 31, 29])

In [23]:
new_data = np.array([[17, 9, 1],
                [21, 10, 1],
                [12, 17, 1]])
new_data @ np.array([4, 5, -100])

array([13, 34, 33])